### PR TITLE
Update embark.vim

### PR DESCRIPTION
**Pull request by Dakai**
Set color space0 to #666666 for better readability.

### CODE REVIEW

**Comment by skbolton** [comment]
I personally don't agree with this being more readable so I would need convincing. This highlight is used in a few places one of which is the cursorline. Having this be a lighter color hurts readability in my opinion.

image

If there is an example you can give of where you think readability is poor we can take a look at switching the code it points to, but I don't think changing this color all over is the answer here.

**Comment by Dakai** [comment]
Thank you very much for your detailed reply and this wonderful theme, I have been using it for several months and it is just so pleasant to look at in vim/neovim.

I didn't notice the cursor line highlighting, but the change was meant to highlight all the exact words/variables,
which is very helpful in coding.

comparison

I am sorry I am a newbie here on the Vim theme scripting, I just found that changing that color could achieve the effect,
and yes, it is probably a bad idea to change the main color setting for this.

**Comment by skbolton** [comment]
Thanks for the kind words @Dakai 
For that highlight you are showing is that different than a highlight search pattern? For me triggering a search gives this

image

**Comment by skbolton** [comment]
If you add this function in your (n)vim and then invoke it while your cursor is over that highlight we can see what group is being applied to that element.

```vimscript
function! SynGroup()
  let l:s = synID(line('.'), col('.'), 1)
  echo synIDattr(l:s, 'name') . ' -> ' . synIDattr(synIDtrans(l:s), 'name')
endfun
```

**Comment by skbolton** [comment]
Also @Dakai this might interest you. I agonized over getting the visual selection highlight right. I wanted it to be obvious that you had selected something without making the underlying text hard to read. Instead of `#666` try the `s:space3` color. I bet you will like that more.

**Comment by Dakai** [comment]
Thanks for your patience, I tried the `s:space3` color, yes, it is so much better! Thank you!

As for the search highlighting, it is not automatic, and it can not differentiate similar variables:



As for the automatic highlighting, I think it is invoked by another syntax plugin, the SynGroup function only shows the latest block containing the element while the highlighting is invoked in larger blocks.



Anyway, thank you for your time and suggestions. I think I should close the request.

**Comment by Dakai** [comment]
Thank you very much for your detailed reply.
I didn't notice the cursor line highlighting, but the change was meant to
highlight all the exact words,which is very helpful in coding.
I am sorry I am a newbie here on the Vim theme script, I just found that
changing that color could achieve this effect,and yes, it is probably a bad idea
to change the main color setting for this.  





On Sat, Jul 30, 2022 at 11:30 AM Stephen Bolton ***@***.***> 
wrote:


I personally don't agree with this being more readable so I would need
convincing. This highlight is used in a few places one of which is the
cursorline. Having this be a lighter color hurts readability in my opinion.



If there is an example you can give of where you think readability is poor we
can take a look at switching the code it points to, but I don't think changing
this color all over is the answer here.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: 
***@***.***>

**Pull request closed without merging**
