### PR TITLE
Add lualine theme support

### PR DESCRIPTION
**Pull request by i40west**
Adds [Lualine](https://github.com/nvim-lualine/lualine.nvim) theme support.

### CODE REVIEW

**Comment by skbolton** [comment]
Thanks for the contribution @i40west. I am not a lualine user so is there anyway I can ask that you add a screenshot as a comment here?

**Comment by i40west** [comment]
Sure! Here are shots of the status bar:

normal
insert
visual

**Comment by i40west** [comment]
Which made me realize I totally spaced on Replace mode. Updated the PR.

replace

**Comment by skbolton** [comment]
how about leveraging the blue for replace mode?

**Comment by i40west** [comment]
blue replace

Yes, I see your point, I was kind of going for similarity with the Airline theme (and thinking, okay, typing is now destructive).

**Comment by skbolton** [comment]
Yeah airline is very out of sate as I never was a user of it. I like where this settled. Thanks for the contribution!

**Pull request merged**
