### PR TITLE
fix typo: change 'underdash' to 'underline'

### PR DESCRIPTION
**Pull request by PerpetualCreativity**
Fixes issue #53.

### CODE REVIEW

**Comment by skbolton** [comment]
Interesting I wonder how this option isn't cross compatible. Maybe it's nvim only? Anyways thanks for the fix!

**Comment by PerpetualCreativity** [comment]
@skbolton I'm running the nightly version of neovim and getting the 'Illegal value: underdash' error. Are you running a GUI version of neovim? I know that (some of?) those support the gui `undercurl` option.

**Comment by skbolton** [comment]
No just neovim in kitty terminal. The help docs `:help hi` have this

```
	Note that "bold" can be used here and by using a bold font.  They
	have the same effect.
	"undercurl", "underdouble", "underdotted", and "underdashed" fall back
	to "underline" in a terminal that does not support them. The color is
```
So I thought it was safe. But either way I have merged your change. The issue no longer persists right?

**Comment by skbolton** [comment]
Oh it is underdashed not underdash....
Strange that I never saw an error pop up.

**Comment by PerpetualCreativity** [comment]
I don't have the issue anymore, but it might make sense to go back to underdash*ed* :)

**Comment by skbolton** [comment]
I am okay with it how we have it. I was getting a little overly fancy

**Pull request merged**
